### ISSUE TITLE
buttons problem

### ISSUE THREAD

**Issue by zonex5** [trueicecold/phaser-scrollable#2]
I can't click teh buttons and sprites in the scroller

**Comment by GregoryBabonaux** [comment]
Same issue for me, use a make.button, then add it as a child to the plugin seems to remove button action.

Any solution ?

**Comment by emik** [comment]
Same issue, had to manually add logic to track input against the button positions and run relevant callbacks.

**Comment by itsay** [comment]
@emik could you share your code?

**Comment by emik** [comment]
@itsay I really wouldn't recommend doing it my way because it was very hacky (small project, quick fix) and I edited the source code.

But if you also just need a quick fix and can edit the source guilt-free, I added a new param "btns" to the constructor
`var ScrollableArea = function (x, y, w, h, params, btns) {`
And inside that set `this.btns = btns;`

In my case `btns` is an array of my own button class objects, where each object has a 'btn' property that is set to a Phaser button.

I then added the following to `beginMove`

```
this.currentClickBtn = null;
  this.btns.forEach(btnObj => {
    if (btnObj.btn.getBounds().contains(this.startX, this.startY)) {
      this.currentClickBtn = btnObj;
    }
  });
```

and this to `endMove` where `id` is an id I manually assigned to the buttons:
```

  this.btns.forEach(btnObj => {
    if (
      btnObj.btn.getBounds().contains(this.game.input.x, this.game.input.y) &&
      this.currentClickBtn &&
      btnObj.id === this.currentClickBtn.id &&
      this.game.input.y - this.startY < 1 &&
      this.game.input.x - this.startX < 1
    ) {
      btnObj.clickBtn();
    }
  });
  this.currentClickBtn = null;
```
